#!/usr/bin/env bash
#
# Copyright 2005-2008, 2011 VMware, Inc.  All rights reserved.
#
# Wrapper for appLoaderized ThinPrint .print Engine CUPS filter, allowing us to
# play tricks with appLoader's argv[0]-based main library detection.

set -e

ETCDIR=/etc/vmware
. $ETCDIR/bootstrap

libdir="$LIBDIR/vmware"

#
# Per CUPS filter(7) manpage:
#    "The command name (argv[0]) is set to the name of the destination printer
#    but is also available in the PRINTER environment variable."
#
# In other words, without this wrapper CUPS invokes appLoader with argv[0] set
# to a printer destination, like HP-LaserJet-4250.  This results in appLoader
# trying to map libHP-LaserJet-4250.so as the library containing main(), and
# is totally not what we want.
#
# thnucups may either be invoked as a standalone program (e.g. to determine its
# version or usage syntax) or as a CUPS filter.  We'll test the existence of an
# arbitrary CUPS variable and PRINTER to determine the appropriate invocation.
#

if [ -n "$CUPS_FILETYPE" -a -n "$PRINTER" ]; then
   exec -a "$PRINTER" "$libdir/bin/appLoader" "$@" -- --argv0=libthnucups.so
else
   exec -a thnucups "$libdir/bin/appLoader" "$@"
fi
